This workflow graph cannot be shown
A graph will be generated the next time this workflow is run.

Annotations
1 error
Invalid workflow file: .github/workflows/main.yml#L1
(Line: 65, Col: 14): Unrecognized named-value: 'item'. Located at position 1 within expression: item.worker
